### ISSUE TITLE
refs of branch lines are shown while branch lines itself aren't rendered

### ISSUE THREAD

**Issue by emiriku** [OpenRailwayMap/OpenRailwayMap-CartoCSS#18]
In zoom level 8, branch lines are not rendered, while their ref is rendered.

**Comment by DerDakon** [comment]
Can you given an example?

**Comment by DerDakon** [comment]
![branch](https://user-images.githubusercontent.com/10909049/72941288-e1136e80-3d70-11ea-8575-83291cffda49.png)

**Comment by Nakaner** [comment]
The bug is located [here](https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/blob/master/project.mml#L203). OpenRailwayMap should start rendering branch lines on zoom level 8, not 9 because the background map renders all `railway=rail` on zoom level >= 8.
