### ISSUE TITLE
Proposed electrification should be rendered different than finished electrification

### ISSUE THREAD

**Issue by JJJWegdam** [OpenRailwayMap/OpenRailwayMap-CartoCSS#35]
At the moment, electrification proposal tags seem to be rendered exactly the same as regular electrification tags. An example is found in Yorkshire, England: [the Huddersfield line](https://tiles.openrailwaymap.org/#osm.org/18/53.680184/-1.730080&overlays=electrification). Its tagging combination is:
`proposed:electrified=contact_line`
`proposed:frequency=50`
`proposed:voltage=25000`

**Comment by DerDakon** [comment]
See #24. This is the main reason that style is not on the front page already.

**Comment by JJJWegdam** [comment]
Oh sorry. I missed that
