### ISSUE TITLE
Electrification layer rendered 20kV AC as gray.

### ISSUE THREAD

**Issue by Jyunhou** [OpenRailwayMap/OpenRailwayMap-CartoCSS#42]
I load electrification layer from `tiles.openrailwaymap.org/electrification/x/y/z.png`,
The electrified rail (20kV AC) is widely used in [north Japan](https://www.openrailwaymap.org/?lang=null&lat=38.27733783109819&lon=140.9593105316162&zoom=13&style=electrification) (50Hz)
![image](https://user-images.githubusercontent.com/45530478/99880035-ddc86800-2c4b-11eb-9fec-185ca3d894cc.png)
and in [southwest Japan](https://www.openrailwaymap.org/?lang=null&lat=33.38974288164124&lon=130.53766250610352&zoom=12&style=electrification) (60Hz)
![image](https://user-images.githubusercontent.com/45530478/99880090-3861c400-2c4c-11eb-9258-37985a464f89.png)
Both of them are rendered as gray, they look like just `No information`.

**Comment by DerDakon** [comment]
@Nakaner I think the reason is ```[frequency=null][frequency!=0]```, where the first should be ```!=```

**Comment by DerDakon** [comment]
Should all be fixed by merging #57, at least I see the given areas in Japan now updated.
