### ISSUE TITLE
Add Color Difference Between ~12kV/25Hz and ~12kV/60Hz

### ISSUE THREAD

**Issue by danieldjewell** [OpenRailwayMap/OpenRailwayMap-CartoCSS#56]
I hope this is the right project to open this in...

The current electrification color scheme doesn't distinguish between ~11-12.5kV at 25Hz and at 60Hz. 

The Northeast Corridor (between Boston, MA and Washington, D.C.) is (sadly) the only fully electrified route of consequence in the United States... Thanks to history, it has 3 voltages/frequencies:

* ~12kV / 25Hz [from Washington D.C. to NYC]
* ~12kV / 60Hz [from NYC to New Haven, CT] 
* 25kV/60Hz [New Haven to Boston] 

The color of both the 12kV lines (at 25 and 60Hz) are the same lime green color. It would be good to create a distinction for these. (If you turn on the "electrification" layer in ORM and zoom in on NYC you'll see the 25Hz line leaving to the west/south of Manhattan and the 60Hz line leaving to the East/North of Manhattan... It's currently a lime green color.)

I know this is one of those somewhat unique fringe cases (I'm not aware of any other country that uses 25Hz railway electrification?) and isn't a major difference like 16.7Hz vs 50 Hz in Europe ... but nonetheless, it would be a nice addition.

**Comment by DerDakon** [comment]
This should be fixed now that #57 is merged, no?

**Comment by TrainTraveler** [comment]
Yes, from my point of view it seems to be fixed.
