### ISSUE TITLE
"etcs=no" takes priority over "construction:etcs=2" in rendering?

### ISSUE THREAD

**Issue by davide84** [OpenRailwayMap/OpenRailwayMap-CartoCSS#91]
Hi,

I have updated the tags of a Bulgarian line where ETCS construction has started. The tiles have been updated but the line is still rendered in black as "no protection", the construction of etcs only shows up in sidings where the other tags were not set.

Example:
https://openrailwaymap.org/?style=signals&lat=43.66069248596476&lon=26.381987929344177&zoom=17
(the lightblue was not there before my changes, I take it as a proof that the tiles have been updated)

The lines correctly shown in lightblue have only "construction:railway:etcs=2".
The lines that stayed in black have "etcs=no", "gnt=no", "lzb=no", "pzb=no" and "construction:railway:etcs=2".

I checked that in https://github.com/OpenRailwayMap/OpenRailwayMap/blob/master/styles/signals.mapcss the tag construction:railway:etcs has a higher z-index. I also checked that in https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/blob/master/sql/functions.sql the function railway_train_protection_rank() returns for construction_etcs <> 'no' before even checking the other tags. I don't see obvious errors in the logic, but there seems to be a glitch somewhere.
Based on the comparison with other lines elsewhere, the conflict seems to be between "railway:etcs=no" and "construction:railway:etcs".

**Comment by davide84** [comment]
I was thinking... what if the "no train protection" was completely removed from ORM? Possible motivations:

- it generates issues like this one
- misrepresents reality (e.g. Italy with SSC which does not have a tag but is an ATP)
- requires custom logic that is simple only for certain countries
- implementing more countries will complicate the sql code
- requires exact combinations of multiple tags
- currently it does not work outside of Europe and even here is far from complete
- lines without any TP should slowly disappear in Europe
- does not provide that much additional information compared to "no info"

What do you think?

**Comment by DerDakon** [comment]
Valid points. I still would suggest adding an [explicit tag](https://wiki.openstreetmap.org/wiki/Proposed_features/railway:train_protection) for this, but independently of this we may as well just remove the "no train protection" rendering on the web alltogether. @Nakaner, what do you think?

**Comment by davide84** [comment]
I finally found a fix and tested it with Kosmtik, see https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/pull/93.

But I would still prefer to have the explicit tag... :)

Test: this lightblue line in Bulgaria was black before:
![Screenshot from 2023-01-26 12-01-26](https://user-images.githubusercontent.com/21276516/214820085-f4ff08f8-2b4c-4956-98bf-cea4d9d7884d.png)

**Comment by davide84** [comment]
Changes began to appear online. Thanks :-)
