### ISSUE TITLE
Display label of station name/short-name/ref when railway=station is a way ?

### ISSUE THREAD

**Issue by Daml** [OpenRailwayMap/OpenRailwayMap-CartoCSS#97]
Hello,

I took some time to understand why some stations `name` or `railway:ref` where not rendered.

It seems that's because many french stations are mapped as ways, and are not accounted by the `stations_with_route_counts` SQL query.

Some quick stats :

FR: 2577 nodes, 535 ways, 17 relations
DE: 4282 nodes, 33 ways, 14 relations
CH: 1219 nodes, 19 ways, 12 relations
AT: 833 nodes, 1 ways, 0 relations
BE: 349 nodes, 5 ways, 0 relations

Is it possible to change the (already intensive) query to get those ways ? Or may french mappers should be incited to use nodes instead ?

Thank for your job.

**Comment by DerDakon** [comment]
See the explanation here: https://github.com/OpenRailwayMap/OpenRailwayMap/issues/840#issuecomment-1637015990
